### ISSUE TITLE
Disable progress bar on to_es

### ISSUE THREAD

**Issue by virtustate** [fuyb1992/es_pandas#16]
Is there a way to disable the progress bar when writing a DataFrame to ES?

Thanks

**Comment by fuyb1992** [comment]
show_progress option in to_es function is added in v0.0.17

**Comment by virtustate** [comment]
I get an error using to_es with show_progress=False

Traceback (most recent call last):
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/elasticsearch/helpers/__init__.py", line 304, in parallel_bulk
    for result in pool.imap(
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/elasticsearch/helpers/__init__.py", line 58, in _chunk_actions
    for action, data in actions:
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/es_pandas/es_pandas.py", line 136, in rec_to_actions
    bar.update(i)
TypeError: update() takes 1 positional argument but 2 were given
