### ISSUE TITLE
to_es error with show_progress=False

### ISSUE THREAD

**Issue by virtustate** [fuyb1992/es_pandas#20]
Using version 0.17 to_es gives error with show_progress=False

Traceback (most recent call last):
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/elasticsearch/helpers/__init__.py", line 304, in parallel_bulk
    for result in pool.imap(
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/multiprocessing/pool.py", line 388, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/elasticsearch/helpers/__init__.py", line 58, in _chunk_actions
    for action, data in actions:
  File "/opt/anaconda3/envs/algorithms/lib/python3.8/site-packages/es_pandas/es_pandas.py", line 136, in rec_to_actions
    bar.update(i)
TypeError: update() takes 1 positional argument but 2 were given

**Comment by fuyb1992** [comment]
Thanks for your reminding，you can fix this by updating es_pandas to 0.0.18.  `BarNothing.update(arg)`  -> `BarNothing.update(self, arg)`
