### ISSUE TITLE
AttributeError: module 'progressbar' has no attribute '__version__'

### ISSUE THREAD

**Issue by anatoly-khomenko** [fuyb1992/es_pandas#4]
### Summary

On python 3.6 virtual environment in Ubuntu 14.04.5 LTS after installing es_pandas and progressbar2, I get the error "AttributeError: module 'progressbar' has no attribute '__version__'" when trying to:
`from es_pandas import es_pandas`

### Details

```
root@ns502245:~# source p36/bin/activate
(p36) root@ns502245:~# pip install progressbar2
Requirement already satisfied: progressbar2 in ./p36/lib/python3.6/site-packages (3.50.0)
Requirement already satisfied: six in ./p36/lib/python3.6/site-packages (from progressbar2) (1.13.0)
Requirement already satisfied: python-utils>=2.3.0 in ./p36/lib/python3.6/site-packages (from progressbar2) (2.4.0)
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(p36) root@ns502245:~# python
Python 3.6.9 (default, Nov 19 2019, 14:10:59)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from es_pandas import es_pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/p36/lib/python3.6/site-packages/es_pandas/__init__.py", line 1, in <module>
    from .es_pandas import es_pandas
  File "/root/p36/lib/python3.6/site-packages/es_pandas/es_pandas.py", line 7, in <module>
    if not progressbar.__version__.startswith('3.'):
AttributeError: module 'progressbar' has no attribute '__version__'
```

**Comment by nachtsky1077** [comment]
What's you version of progressbar2? I'm using progressbar2 version 3.50.0 and not having the issue you mentioned. Try upgrading to the latest version and let us know if the issue still exists.

**Comment by igorbrigadir** [comment]
I think something broke with a new version of `progressbar2` but installing an older release solves this for me:

```
pip install --upgrade progressbar2==3.47.0
```
